# -*- coding: utf-8 -*-
"""CSV_generator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sE8gD8DRLXcTpeDIX4Uw5E1HAp4Gfuyw
"""

import csv
import random
from datetime import datetime, timedelta

expenses = [
    'Auto Loan', 'Cable TV', 'Daycare', 'Dental Care', 'Entertainment', 'Groceries',
    'Coffee Shops', 'Shopping', 'Utilities', 'Transportation', 'Health Insurance', 'Books',
    'Gifts', 'Electronics', 'Vacation', 'Medical Expenses', 'Home Improvement',
    'Car Maintenance', 'Subscriptions', 'Furniture', 'Education', 'Donations', 'Music',
    'Insurance', 'Technology', 'Art', 'Fashion', 'Sports', 'Subscription', 'Car Insurance',
    'Travel', 'Healthcare', 'Outdoor Activities', 'Clothing', 'Investment', 'Home Decor',
    'Outdoor Gear', 'Fitness', 'Personal Care', 'Home Appliances', 'Jewelry', 'Luxury Items',
    'Pets', 'Photography', 'Smart Home', 'Virtual Reality', 'Workout Gear', 'Yoga Classes',
    'Outdoor Furniture', 'Sports Equipment', 'Board Games', 'DIY Tools', 'Fine Dining',
    'Concert Tickets', 'Hobbies', 'Ski Trip', 'Art Supplies', 'Biking Gear', 'Camping Equipment',
    'Designer Clothing', 'Fishing Gear', 'Home Theater', 'Kitchen Gadgets', 'Luxury Watches',
    'Outdoor Lighting', 'Personal Trainer', 'Smartphone Accessories', 'Spa Day', 'Theme Park Tickets',
    'Whiskey Collection', 'Wine Tasting', 'Adventure Tours', 'Book Club Membership', 'Coffee Roastery',
    'Escape Room Experience', 'Fly Fishing', 'Hot Air Balloon Ride', 'Museum Memberships',
    'Private Chef Experience', 'Scuba Diving Lessons', 'Train Adventure', 'Virtual Cooking Class',
    'Yacht Rental', 'Zipline Adventure', 'Antique Collectibles', 'Barbecue Essentials',
    'Camping Gear', 'Collectible Coins', 'Distillery Tour', 'Exotic Pet Supplies',
    'Fine Wine Collection', 'Gourmet Chocolate Tasting', 'High-End Art Prints', 'Indoor Plants',
    'Luxury Car Rental', 'Mountain Biking', 'Personalized Jewelry', 'Rare Book Collection',
    'Segway Adventure', 'Smart Home Devices', 'Spa Retreat', 'Supercar Driving Experience',
    'Theater Tickets', 'Vintage Vinyl Records', 'Woodworking Tools', 'Zip Lining Adventure',
    'Aerial Yoga Classes', 'Archery Gear', 'Backpacking Essentials', 'Cheese Tasting',
    'Classic Car Rental', 'Custom Fragrance Creation', 'DIY Home Brewing Kit',
    'Exotic Car Racing Experience', 'Fashion Design Course', 'Golf Lessons',
    'Horseback Riding Adventure', 'Hot Stone Massage', 'Interior Design Consultation',
    'Kayaking Expedition', 'Luxury Picnic Experience', 'Motorcycle Adventure', 'Olive Oil Tasting',
    'Personalized Artwork', 'Racing Simulator Session', 'Sailing Adventure', 'Scenic Helicopter Tour',
    'Skydiving Experience', 'Stand-Up Comedy Show', 'Superyacht Charter', 'Thai Cooking Class',
    'Truffle Hunting Tour', 'Vintage Champagne Tasting', 'Wildlife Safari', 'Windsurfing Lesson',
    'Yoga Retreat', 'Zookeeper for a Day', '3D Printing Workshop', 'Antique Map Collection',
    'Backyard Beekeeping Kit', 'Bonsai Tree Starter Kit', 'Culinary Walking Tour',
    'Luxury', 'Home Entertainment', 'Car Rental', 'Restaurant', 'Donation', 'School Payments',
    'Pool and Entertainment', 'Karting', 'Home Maintenance', 'Pet Care', 'Child Education',
    'Professional Development', 'Beauty Services', 'Social Events', 'Electrical Bills',
    'Water Bills', 'Gas Bills', 'Phone Bills', 'Internet Bills', 'Home Security',
    'Gardening Supplies', 'Craft Supplies', 'Gaming Expenses', 'Savings Contributions',
    'Retirement Contributions', 'Emergency Fund', 'Tax Payments', 'Home Insurance',
    'Personal Development', 'Charity Contributions', 'Home Office Expenses', 'Networking Events',
    'Craftsmanship Tools', 'Luxury Travel', 'Digital Subscriptions', 'Home Renovation',
    'Smart Technology', 'Hiking Gear'
]

incomes = [
    'Salary', 'Freelance Income', 'Investment Returns', 'Bonus', 'Commission',
    'Rental Income', 'Side Hustle', 'Online Sales', 'Consulting Fees', 'Dividends',
    'Gift Income', 'Scholarships', 'Grants', 'Royalties', 'Refunds', 'Allowances',
    'Interest Income', 'Cashback Rewards', 'Alimony', 'Child Support', 'Tax Refund',
    'Social Security', 'Pension', 'Stock Sales', 'Real Estate Income', 'Part-time Job',
    'Vendor Payments', 'Crowdfunding Income', 'Teaching/Tutoring Income', 'Inheritance'
]

# Function to generate a random datetime
def random_datetime(start_date, end_date):
    time_delta = end_date - start_date
    random_days = random.randint(0, time_delta.days)
    random_seconds = random.randint(0, 24*60*60-1)
    return start_date + timedelta(days=random_days, seconds=random_seconds)

# Function to generate a random amount
def random_amount(category):
    if category in expenses:
        return round(random.uniform(-1, -10000), 2)
    elif category in incomes:
        return round(random.uniform(0.1, 100000), 2)

# Function to generate a CSV file
def generate_csv(file_path, num_lines):
    start_date = datetime(2013, 1, 1)
    end_date = datetime.now()

    with open(file_path, 'w', newline='') as csvfile:
        fieldnames = ['Date', 'Description', 'Category', 'Amount']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

        writer.writeheader()

        for i in range(1, num_lines + 1):
            date = random_datetime(start_date, end_date)
            description = f'Transaction {i}'
            category = random.choice(expenses + incomes)
            amount = random_amount(category)
            writer.writerow({
                'Date': date.strftime('%Y-%m-%d %H:%M:%S'),
                'Description': description,
                'Category': category,
                'Amount': f'${amount:,.2f}' if amount >= 0 else f'-${abs(amount):,.2f}'
            })

generate_csv('transactions.csv', 50000)

